# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2
build:
    os: ubuntu-20.04
    tools:
        python: "3.7"
sphinx:
    configuration: docs/conf.py
python:
    install:
        - method: pip
          path: .
	  requirements: requirements.txt
          extra_requirements:
              - doc
